name: pipeline-action
on:
  workflow_dispatch:
jobs:
  test_pipeline:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: "actions/checkout@master"
        - name: test
          run: echo its working